let
    Source = Excel.CurrentWorkbook(){[Name="vehicles_rawdata"]}[Content],
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"barrels08", type number}, {"barrelsA08", Int64.Type}, {"charge120", Int64.Type}, {"charge240", Int64.Type}, {"city08", Int64.Type}, {"city08U", Int64.Type}, {"cityA08", Int64.Type}, {"cityA08U", Int64.Type}, {"cityCD", Int64.Type}, {"cityE", Int64.Type}, {"cityUF", Int64.Type}, {"co2", Int64.Type}, {"co2A", Int64.Type}, {"co2TailpipeAGpm", Int64.Type}, {"co2TailpipeGpm", type number}, {"comb08", Int64.Type}, {"comb08U", Int64.Type}, {"combA08", Int64.Type}, {"combA08U", Int64.Type}, {"combE", Int64.Type}, {"combinedCD", Int64.Type}, {"combinedUF", Int64.Type}, {"cylinders", Int64.Type}, {"displ", type number}, {"drive", type text}, {"engId", Int64.Type}, {"eng_dscr", type text}, {"feScore", Int64.Type}, {"fuelCost08", Int64.Type}, {"fuelCostA08", Int64.Type}, {"fuelType", type text}, {"fuelType1", type text}, {"ghgScore", Int64.Type}, {"ghgScoreA", Int64.Type}, {"highway08", Int64.Type}, {"highway08U", Int64.Type}, {"highwayA08", Int64.Type}, {"highwayA08U", Int64.Type}, {"highwayCD", Int64.Type}, {"highwayE", Int64.Type}, {"highwayUF", Int64.Type}, {"hlv", Int64.Type}, {"hpv", Int64.Type}, {"id", Int64.Type}, {"lv2", Int64.Type}, {"lv4", Int64.Type}, {"make", type text}, {"model", type any}, {"mpgData", type text}, {"phevBlended", type logical}, {"pv2", Int64.Type}, {"pv4", Int64.Type}, {"range", Int64.Type}, {"rangeCity", Int64.Type}, {"rangeCityA", Int64.Type}, {"rangeHwy", Int64.Type}, {"rangeHwyA", Int64.Type}, {"trany", type text}, {"UCity", type number}, {"UCityA", Int64.Type}, {"UHighway", type number}, {"UHighwayA", Int64.Type}, {"VClass", type text}, {"year", Int64.Type}, {"youSaveSpend", Int64.Type}, {"guzzler", type text}, {"trans_dscr", type text}, {"tCharger", type text}, {"sCharger", type text}, {"atvType", type text}, {"fuelType2", type any}, {"rangeA", type any}, {"evMotor", type any}, {"mfrCode", type any}, {"c240Dscr", type any}, {"charge240b", Int64.Type}, {"c240bDscr", type any}, {"createdOn", type text}, {"modifiedOn", type text}, {"startStop", type any}, {"phevCity", Int64.Type}, {"phevHwy", Int64.Type}, {"phevComb", Int64.Type}})
in
    #"Changed Type"